name: midia_select
description: A new Flutter package project.
version: 0.0.1
homepage:
publish_to: 'none'

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  file_picker_cross: ^4.4.2
  msk_utils: ^0.0.4-dev.1
  image_picker: ^0.8.3+2
  flutter_mobx: ^2.0.2
  pinch_zoom_image_last: ^0.4.1
  carousel_slider: ^4.0.0
  cached_network_image: ^3.1.0
  mobx: ^2.0.4
  bloc_pattern: ^3.0.0
  flutter:
    sdk: flutter

dev_dependencies: 
  build_runner: ^2.1.1
  mobx_codegen: ^2.0.3
  flutter_test:
    sdk: flutter