name: midia_select
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  msk_utils:
    #path: /Users/reni/Downloads/Projetos/MSK/flutter/msk_plugin/msk_utils
    git:
      url: git@github.com:ReniDelonzek/msk_utils.git
      ref: 4cc07229ffeb88d39832cd98554641185f3c24e2

  image_picker: ^0.6.6+1
  flutter_mobx: ^0.3.3+3
  pinch_zoom_image_last: ^0.3.1
  carousel_slider: ^2.1.0
  cached_network_image: ^2.2.0+1
  mobx: ^0.3.9+3
  bloc_pattern: ^2.5.1
  flutter:
    sdk: flutter

dev_dependencies: 
  build_runner: ^1.10.0
  mobx_codegen: ^0.3.10+1
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages